"""
---------------------------------------------------------------
File name:                  main.py
Author:                     Ignorant-lu
Date created:               2025/04/15
Description:                Sprite Mask Editor 应用程序入口点
----------------------------------------------------------------

Changed history:            
                            2025/04/15: 初始创建;
----
"""
import sys
from PyQt6 import QtWidgets
from .main_window import SpriteMaskEditor


# Assuming resources are handled, e.g., compiled via pyrcc
# If you have a resources.py generated by pyrcc, uncomment the next line
# import resources 


def main():
    app = QtWidgets.QApplication(sys.argv)
    
    # 设置应用样式 (可以从 main_window.py 或单独文件加载)
    style = """
    QMainWindow, QDialog {
        background-color: #f7f9fb;
    }
    QGroupBox {
        border: 1px solid #bbb;
        border-radius: 6px;
        margin-top: 12px;
        font-weight: bold;
        color: #333;
    }
    QGroupBox::title {
        subcontrol-origin: margin;
        left: 10px;
        padding: 0 5px;
    }
    QLabel {
        font-size: 14px;
        color: #333;
    }
    QPushButton, QToolButton {
        background: #4f8cff;
        color: #fff;
        border-radius: 4px;
        padding: 6px 12px; /* Adjusted padding */
        font-weight: bold;
        border: none;
        min-height: 28px; /* Ensure minimum height */
    }
    QPushButton:hover, QToolButton:hover {
        background: #3a75e6;
    }
    QPushButton:pressed, QToolButton:pressed {
        background: #2a65d6;
    }
    QPushButton:disabled, QToolButton:disabled {
        background: #b0b0b0;
    }
    QToolButton {
        padding: 4px; /* Smaller padding for tool buttons */
    }
    QToolButton:checked {
        background: #2a65d6;
    }
    QSlider::groove:horizontal {
        height: 8px;
        background: #eee;
        border-radius: 4px;
    }
    QSlider::handle:horizontal {
        background: #4f8cff;
        border-radius: 8px;
        width: 18px;
        height: 18px;
        margin: -5px 0;
    }
    QTabWidget::pane {
        border: 1px solid #bbb;
        border-radius: 0 6px 6px 6px; /* Adjust radius */
        top: -1px;
        background: white;
    }
    QTabBar::tab {
        background: #e0e5ea;
        border: 1px solid #bbb;
        border-bottom: none; /* Remove bottom border */
        border-top-left-radius: 4px;
        border-top-right-radius: 4px;
        min-width: 8ex;
        padding: 8px 12px;
        color: #333;
        margin-right: 2px;
    }
    QTabBar::tab:selected {
        background: white;
        border-color: #bbb;
        border-bottom-color: white; /* Match pane background */
        margin-bottom: -1px; /* Align with pane */
    }
    QScrollArea {
        border: none;
    }
    QLineEdit, QSpinBox, QDoubleSpinBox {
        padding: 5px;
        border: 1px solid #bbb;
        border-radius: 4px;
        background: white;
        min-height: 20px; /* Ensure consistent height */
    }
    QComboBox {
        padding: 5px;
        border: 1px solid #bbb;
        border-radius: 4px;
        background: white;
        min-height: 20px;
    }
    QProgressDialog {
        background-color: #f7f9fb;
        border: 1px solid #bbb;
        border-radius: 6px;
    }
    QStatusBar {
        background-color: #f0f2f5;
        color: #333;
    }
    QSplitter::handle {
        background-color: #d0d5db;
    }
    QSplitter::handle:horizontal {
        width: 2px;
    }
    QSplitter::handle:vertical {
        height: 2px;
    }
    QToolTip {
        background-color: #ffffe0; /* Light yellow */
        color: #333;
        border: 1px solid #aaa;
        padding: 4px;
        border-radius: 3px;
    }
    QMenu {
        background-color: white;
        border: 1px solid #bbb;
        border-radius: 4px;
    }
    QMenu::item {
        padding: 5px 20px 5px 20px;
    }
    QMenu::item:selected {
        background-color: #e0e5ea;
    }
    QMenu::separator {
        height: 1px;
        background-color: #bbb;
        margin-left: 10px;
        margin-right: 10px;
    }
    """
    app.setStyleSheet(style)
    
    # 创建并显示主窗口
    main_window = SpriteMaskEditor()
    main_window.show()
    
    # 运行事件循环
    sys.exit(app.exec())

if __name__ == '__main__':
    main()
